### ISSUE TITLE
Cancel Button Not Working

### ISSUE THREAD

**Issue by MarioneDev** [miguelflores-0906/CSSWENG-GROUP-4-ADMIN-SIDE#3]
**Summary:**
The Add Expense's "Cancel" button is non-functional
**Steps to Reproduce:**
Fill out the Add Expense form and click on the "Cancel" button
**Expected Results:**
User alerted of the cancellation / Add Expense form fields cleared
**Actual Results:**
No prompt for user / fields not cleared
**Recommendation:**
Add an alert or clear the Add Expense form fields when "Cancel" button is pressed
 
Info | Value
-- | --
Browser | Microsoft Edge
Screen Size | 1920x1080
Zoom | 100%

![image](https://user-images.githubusercontent.com/77104665/133328192-6f7670cd-a02c-4cee-865e-602325870ab3.png)

**Comment by miguelflores-0906** [comment]
cancel button now redirects back to the finance page where the user can click on "add expense" btn to go back to this screen.
