### ISSUE TITLE
Add Revenue: "Payment" field accepts any input

### ISSUE THREAD

**Issue by migsszz** [miguelflores-0906/CSSWENG-GROUP-4-ADMIN-SIDE#5]
**Summary:**
Database accepts any value inside payment field.
**Steps to Reproduce:**
Input any value inside payment field on add payment.
**Expected Results:**
Values are not passed to database or error should show.
**Actual Results:**
Any values are accepted and passed into the database.
**Recommendation:**
Either use error checking function to check for Partial or Full or use a dropdown box. 

| Info  | Value |
| ------------- | ------------- |
| Browser  | Google Chrome |
| Screen Size  | 1920x1080 |
| Zoom  | 100% |

![issuerevenue](https://user-images.githubusercontent.com/33576804/134019206-a0749b83-ecfa-4b3e-8085-9af3a77c8c3d.PNG)

**Comment by miguelflores-0906** [comment]
Goods as well
